/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IDEX, IDEXInterface } from "../../../contracts/socialfi/IDEX";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
    ],
    name: "delist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from_",
        type: "address",
      },
    ],
    name: "fee",
    outputs: [
      {
        internalType: "uint256",
        name: "listFee_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
    ],
    name: "list",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "takerId_",
        type: "uint256",
      },
    ],
    name: "takerFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDEX__factory {
  static readonly abi = _abi;
  static createInterface(): IDEXInterface {
    return new utils.Interface(_abi) as IDEXInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IDEX {
    return new Contract(address, _abi, signerOrProvider) as IDEX;
  }
}
