/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITakerReceiver,
  ITakerReceiverInterface,
} from "../../../contracts/socialfi/ITakerReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "takerId_",
        type: "uint256",
      },
    ],
    name: "takerFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITakerReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): ITakerReceiverInterface {
    return new utils.Interface(_abi) as ITakerReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITakerReceiver {
    return new Contract(address, _abi, signerOrProvider) as ITakerReceiver;
  }
}
