/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Taker, TakerInterface } from "../../../contracts/socialfi/Taker";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from_",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "responseSkuQuantityOrId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "responsePriceQuantityOrId_",
        type: "uint256",
      },
    ],
    name: "TakerBurn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from_",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "requestSkuQuantityOrId_",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "requestPriceQuantityOrId_",
        type: "uint256",
      },
    ],
    name: "TakerMint",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index_",
        type: "uint256",
      },
    ],
    name: "takerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "takerId_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "takerId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "responseSkuQuantityOrId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "responsePriceQuantityOrId_",
        type: "uint256",
      },
    ],
    name: "takerCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "takerId_",
        type: "uint256",
      },
    ],
    name: "takerMetadata",
    outputs: [
      {
        internalType: "address",
        name: "maker_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "makerId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "requestSkuQuantityOrId_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "requestPriceQuantityOrId_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupplyOfTaker",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Taker__factory {
  static readonly abi = _abi;
  static createInterface(): TakerInterface {
    return new utils.Interface(_abi) as TakerInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Taker {
    return new Contract(address, _abi, signerOrProvider) as Taker;
  }
}
