/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDEX } from "./IDEX";
export type { IMaker } from "./IMaker";
export type { ISocialWallet } from "./ISocialWallet";
export type { ITaker } from "./ITaker";
export type { ITakerReceiver } from "./ITakerReceiver";
export type { Maker } from "./Maker";
export type { SocialWallet } from "./SocialWallet";
export type { Taker } from "./Taker";
export type { TakerReceiver } from "./TakerReceiver";
