/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IMaker {
  export type MetadataStruct = {
    sku: PromiseOrValue<string>;
    skuQuantityOrId: PromiseOrValue<BigNumberish>;
    paymentCurrency: PromiseOrValue<string>;
    priceQuantityOrId: PromiseOrValue<BigNumberish>;
    skuType: PromiseOrValue<BigNumberish>;
    paymentCurrencyType: PromiseOrValue<BigNumberish>;
  };

  export type MetadataStructOutput = [
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    sku: string;
    skuQuantityOrId: BigNumber;
    paymentCurrency: string;
    priceQuantityOrId: BigNumber;
    skuType: BigNumber;
    paymentCurrencyType: BigNumber;
  };
}

export interface SocialWalletInterface extends utils.Interface {
  functions: {
    "approveDex(uint256,address)": FunctionFragment;
    "closeMaker(uint256)": FunctionFragment;
    "closeTaker(uint256)": FunctionFragment;
    "makerByIndex(uint256)": FunctionFragment;
    "makerMetadata(uint256)": FunctionFragment;
    "mintMaker((address,uint256,address,uint256,uint128,uint128),address)": FunctionFragment;
    "mintTaker(address,address,uint256,uint256,uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "takerByIndex(uint256)": FunctionFragment;
    "takerCallback(uint256,uint256,uint256)": FunctionFragment;
    "takerFrom(address,uint256)": FunctionFragment;
    "takerMetadata(uint256)": FunctionFragment;
    "totalSupplyOfMaker()": FunctionFragment;
    "totalSupplyOfTaker()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "approveDex"
      | "closeMaker"
      | "closeTaker"
      | "makerByIndex"
      | "makerMetadata"
      | "mintMaker"
      | "mintTaker"
      | "supportsInterface"
      | "takerByIndex"
      | "takerCallback"
      | "takerFrom"
      | "takerMetadata"
      | "totalSupplyOfMaker"
      | "totalSupplyOfTaker"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveDex",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "closeMaker",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "closeTaker",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "makerByIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "makerMetadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintMaker",
    values: [IMaker.MetadataStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTaker",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "takerByIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "takerCallback",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "takerFrom",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "takerMetadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOfMaker",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyOfTaker",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "approveDex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeMaker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeTaker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makerMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintMaker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintTaker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takerCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "takerFrom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "takerMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOfMaker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyOfTaker",
    data: BytesLike
  ): Result;

  events: {
    "MakerBurn(address,uint256)": EventFragment;
    "MakerMint(address,uint256,address)": EventFragment;
    "MakerUpdate(address,uint256,uint256,uint256)": EventFragment;
    "TakerBurn(address,uint256,uint256,uint256)": EventFragment;
    "TakerMint(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MakerBurn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MakerMint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MakerUpdate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerBurn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TakerMint"): EventFragment;
}

export interface MakerBurnEventObject {
  from_: string;
  tokenId_: BigNumber;
}
export type MakerBurnEvent = TypedEvent<
  [string, BigNumber],
  MakerBurnEventObject
>;

export type MakerBurnEventFilter = TypedEventFilter<MakerBurnEvent>;

export interface MakerMintEventObject {
  from_: string;
  tokenId_: BigNumber;
  dex_: string;
}
export type MakerMintEvent = TypedEvent<
  [string, BigNumber, string],
  MakerMintEventObject
>;

export type MakerMintEventFilter = TypedEventFilter<MakerMintEvent>;

export interface MakerUpdateEventObject {
  from_: string;
  tokenId_: BigNumber;
  settleSkuQuantityOrId_: BigNumber;
  settlePaymentOrId_: BigNumber;
}
export type MakerUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  MakerUpdateEventObject
>;

export type MakerUpdateEventFilter = TypedEventFilter<MakerUpdateEvent>;

export interface TakerBurnEventObject {
  from_: string;
  tokenId_: BigNumber;
  responseSkuQuantityOrId_: BigNumber;
  responsePriceQuantityOrId_: BigNumber;
}
export type TakerBurnEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TakerBurnEventObject
>;

export type TakerBurnEventFilter = TypedEventFilter<TakerBurnEvent>;

export interface TakerMintEventObject {
  from_: string;
  tokenId_: BigNumber;
  requestSkuQuantityOrId_: BigNumber;
  requestPriceQuantityOrId_: BigNumber;
}
export type TakerMintEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  TakerMintEventObject
>;

export type TakerMintEventFilter = TypedEventFilter<TakerMintEvent>;

export interface SocialWallet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SocialWalletInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveDex(
      makerId_: PromiseOrValue<BigNumberish>,
      to_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeMaker(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    closeTaker(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    makerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { makerId_: BigNumber }>;

    makerMetadata(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IMaker.MetadataStructOutput, BigNumber, BigNumber, string] & {
        maker_: IMaker.MetadataStructOutput;
        sentSkuQuantityOrId_: BigNumber;
        receivedPaymentQuantityOrId_: BigNumber;
        dex_: string;
      }
    >;

    mintMaker(
      maker_: IMaker.MetadataStruct,
      dex_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintTaker(
      depsoitFrom_: PromiseOrValue<string>,
      maker_: PromiseOrValue<string>,
      makerId_: PromiseOrValue<BigNumberish>,
      requestSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      requestPriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    takerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { takerId_: BigNumber }>;

    takerCallback(
      takerId_: PromiseOrValue<BigNumberish>,
      responseSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      responsePriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    takerFrom(
      from_: PromiseOrValue<string>,
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    takerMetadata(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        maker_: string;
        makerId_: BigNumber;
        requestSkuQuantityOrId_: BigNumber;
        requestPriceQuantityOrId_: BigNumber;
      }
    >;

    totalSupplyOfMaker(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { totalSupply_: BigNumber }>;

    totalSupplyOfTaker(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { totalSupply_: BigNumber }>;
  };

  approveDex(
    makerId_: PromiseOrValue<BigNumberish>,
    to_: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeMaker(
    makerId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  closeTaker(
    takerId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  makerByIndex(
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  makerMetadata(
    makerId_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [IMaker.MetadataStructOutput, BigNumber, BigNumber, string] & {
      maker_: IMaker.MetadataStructOutput;
      sentSkuQuantityOrId_: BigNumber;
      receivedPaymentQuantityOrId_: BigNumber;
      dex_: string;
    }
  >;

  mintMaker(
    maker_: IMaker.MetadataStruct,
    dex_: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintTaker(
    depsoitFrom_: PromiseOrValue<string>,
    maker_: PromiseOrValue<string>,
    makerId_: PromiseOrValue<BigNumberish>,
    requestSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
    requestPriceQuantityOrId_: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  takerByIndex(
    index_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  takerCallback(
    takerId_: PromiseOrValue<BigNumberish>,
    responseSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
    responsePriceQuantityOrId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  takerFrom(
    from_: PromiseOrValue<string>,
    takerId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  takerMetadata(
    takerId_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      maker_: string;
      makerId_: BigNumber;
      requestSkuQuantityOrId_: BigNumber;
      requestPriceQuantityOrId_: BigNumber;
    }
  >;

  totalSupplyOfMaker(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupplyOfTaker(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    approveDex(
      makerId_: PromiseOrValue<BigNumberish>,
      to_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    closeMaker(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    closeTaker(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    makerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    makerMetadata(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [IMaker.MetadataStructOutput, BigNumber, BigNumber, string] & {
        maker_: IMaker.MetadataStructOutput;
        sentSkuQuantityOrId_: BigNumber;
        receivedPaymentQuantityOrId_: BigNumber;
        dex_: string;
      }
    >;

    mintMaker(
      maker_: IMaker.MetadataStruct,
      dex_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintTaker(
      depsoitFrom_: PromiseOrValue<string>,
      maker_: PromiseOrValue<string>,
      makerId_: PromiseOrValue<BigNumberish>,
      requestSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      requestPriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    takerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    takerCallback(
      takerId_: PromiseOrValue<BigNumberish>,
      responseSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      responsePriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    takerFrom(
      from_: PromiseOrValue<string>,
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    takerMetadata(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        maker_: string;
        makerId_: BigNumber;
        requestSkuQuantityOrId_: BigNumber;
        requestPriceQuantityOrId_: BigNumber;
      }
    >;

    totalSupplyOfMaker(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyOfTaker(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "MakerBurn(address,uint256)"(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null
    ): MakerBurnEventFilter;
    MakerBurn(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null
    ): MakerBurnEventFilter;

    "MakerMint(address,uint256,address)"(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      dex_?: PromiseOrValue<string> | null
    ): MakerMintEventFilter;
    MakerMint(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      dex_?: PromiseOrValue<string> | null
    ): MakerMintEventFilter;

    "MakerUpdate(address,uint256,uint256,uint256)"(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      settleSkuQuantityOrId_?: null,
      settlePaymentOrId_?: null
    ): MakerUpdateEventFilter;
    MakerUpdate(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      settleSkuQuantityOrId_?: null,
      settlePaymentOrId_?: null
    ): MakerUpdateEventFilter;

    "TakerBurn(address,uint256,uint256,uint256)"(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      responseSkuQuantityOrId_?: null,
      responsePriceQuantityOrId_?: null
    ): TakerBurnEventFilter;
    TakerBurn(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      responseSkuQuantityOrId_?: null,
      responsePriceQuantityOrId_?: null
    ): TakerBurnEventFilter;

    "TakerMint(address,uint256,uint256,uint256)"(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      requestSkuQuantityOrId_?: null,
      requestPriceQuantityOrId_?: null
    ): TakerMintEventFilter;
    TakerMint(
      from_?: PromiseOrValue<string> | null,
      tokenId_?: PromiseOrValue<BigNumberish> | null,
      requestSkuQuantityOrId_?: null,
      requestPriceQuantityOrId_?: null
    ): TakerMintEventFilter;
  };

  estimateGas: {
    approveDex(
      makerId_: PromiseOrValue<BigNumberish>,
      to_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeMaker(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    closeTaker(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    makerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    makerMetadata(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintMaker(
      maker_: IMaker.MetadataStruct,
      dex_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintTaker(
      depsoitFrom_: PromiseOrValue<string>,
      maker_: PromiseOrValue<string>,
      makerId_: PromiseOrValue<BigNumberish>,
      requestSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      requestPriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    takerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    takerCallback(
      takerId_: PromiseOrValue<BigNumberish>,
      responseSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      responsePriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    takerFrom(
      from_: PromiseOrValue<string>,
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    takerMetadata(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalSupplyOfMaker(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupplyOfTaker(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    approveDex(
      makerId_: PromiseOrValue<BigNumberish>,
      to_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeMaker(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    closeTaker(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    makerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    makerMetadata(
      makerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintMaker(
      maker_: IMaker.MetadataStruct,
      dex_: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintTaker(
      depsoitFrom_: PromiseOrValue<string>,
      maker_: PromiseOrValue<string>,
      makerId_: PromiseOrValue<BigNumberish>,
      requestSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      requestPriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    takerByIndex(
      index_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    takerCallback(
      takerId_: PromiseOrValue<BigNumberish>,
      responseSkuQuantityOrId_: PromiseOrValue<BigNumberish>,
      responsePriceQuantityOrId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    takerFrom(
      from_: PromiseOrValue<string>,
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    takerMetadata(
      takerId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupplyOfMaker(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalSupplyOfTaker(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
